### ISSUE TITLE
Humidity sensor

### ISSUE THREAD

**Issue by chli** [axlan/sainlogic-sdr#3]
Hi,

For your information, on your blog (https://www.robopenguins.com/weather-station/) the part you thought was an antenna attached to the "RTH" port isn't one.

RTH probably stands for Relative Humidity and the part is a capacitive humidity sensor, maybe a "CON-EFS10" or a similar part.

Best regards,

Christophe

**Comment by axlan** [comment]
Thanks, finally got around to updating the article with this.
